name: flutter_flash_chat
description: Flash Chat App

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^1.3.1
  firebase_core: ^0.4.1+3
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.12.10
  modal_progress_hud: ^0.1.3
  intl: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.9.0
  provider: ^4.3.1
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
